spring:
  application:
    name: MyHotelAssistant
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo-hotel
  task:
    scheduling:
      pool:
        size: 2
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: /tmp
      resolve-lazily: false
logging:
  level:
    inzynierka.myhotelassistant: DEBUG
app:
  notification:
    expiration:
      days: 30
  schedules-generator:
    days-ahead: 21
  upload:
    dir: /var/myhotelassistant/uploads
    max-file-size: 10MB
    allowed-image-types:
      - image/jpeg
      - image/jpg
      - image/png
      - image/webp